using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace KeuAPI.Models
{
    public partial class SasMasterSiswaAll
    {
        public int Id { get; set; }
        public DateTime? DateTime { get; set; }
        public DateTime? Modified { get; set; }
        public string Ip { get; set; }
        public int? Creator { get; set; }
        public int? Modifier { get; set; }
        public string Nospj { get; set; }
        public string Noregpsb { get; set; }
        public string Namasiswa { get; set; }
        public string Agama { get; set; }
        public string Subagama { get; set; }
        public string Tmplahir { get; set; }
        public DateTime? Tgllahir { get; set; }
        public string Jenkel { get; set; }
        public string Namaayah { get; set; }
        public string Namaibu { get; set; }
        public string Namawali { get; set; }
        public string AlamatSiswa { get; set; }
        public string Telpon { get; set; }
        public string Kota { get; set; }
        public string Kodepos { get; set; }
        public string Goldarah { get; set; }
        public string Nis { get; set; }
        public string Nisn { get; set; }
        public string Anakke { get; set; }
        public string Statusdalamkeluarga { get; set; }
        public string Asalsekolah { get; set; }
        public string Diterimakelas { get; set; }
        public DateTime? Diterimatanggal { get; set; }
        public string Pekerjaanayah { get; set; }
        public string Pekerjaanibu { get; set; }
        public string Pekerjaanwali { get; set; }
        public string EmailPenabur { get; set; }
        public string EmailPribadi { get; set; }
        public string HpOrangtua { get; set; }
        public string HpPribadi { get; set; }
        public string EmailAyah { get; set; }
        public string EmailIbu { get; set; }
        public string PasswordEmailPenabur { get; set; }
        public string HpAyah { get; set; }
        public string HpIbu { get; set; }
        public string EmailWali { get; set; }
        public string HpWali { get; set; }
        public string AgamaAyah { get; set; }
        public string AgamaIbu { get; set; }
        public string AgamaWali { get; set; }
        public string StatusAyah { get; set; }
        public string StatusIbu { get; set; }
        public string WnAyah { get; set; }
        public string WnIbu { get; set; }
        public string WnWali { get; set; }
        public string AlamatAyah { get; set; }
        public string AlamatIbu { get; set; }
        public string AlamatWali { get; set; }
        public string Kelurahan { get; set; }
        public string KodeposAyah { get; set; }
        public string KodeposIbu { get; set; }
        public string KodeposWali { get; set; }
        public string KelurahanAyah { get; set; }
        public string KelurahanIbu { get; set; }
        public string KelurahanWali { get; set; }
        public DateTime? TgllahirAyah { get; set; }
        public DateTime? TgllahirIbu { get; set; }
        public DateTime? TgllahirWali { get; set; }
        public string TmplahirAyah { get; set; }
        public string TmplahirIbu { get; set; }
        public string TmplahirWali { get; set; }
        public string TelponAyah { get; set; }
        public string TelponIbu { get; set; }
        public string TelponWali { get; set; }
        public string PreferensiKontak { get; set; }
        public string JumlahSaudaraKandung { get; set; }
        public string JumlahSaudaraTiri { get; set; }
        public string JumlahSaudaraAngkat { get; set; }
        public string AlamatKantorAyah { get; set; }
        public string AlamatKantorIbu { get; set; }
        public string AlamatKantorWali { get; set; }
        public string KotaAyah { get; set; }
        public string KotaIbu { get; set; }
        public string KotaWali { get; set; }
        public string PendidikanAyah { get; set; }
        public string PendidikanIbu { get; set; }
        public string PendidikanWali { get; set; }
        public string JenkelWali { get; set; }
        public string JarakRumah { get; set; }
        public string Transportasi { get; set; }
        public string NamaPanggilan { get; set; }
        public string Kecamatan { get; set; }
        public string Wn { get; set; }
        public string Bahasa { get; set; }
        public int? Idgki { get; set; }
        public string GeoSiswa { get; set; }
        public string LatitudeSiswa { get; set; }
        public string LongitudeSiswa { get; set; }
        public string GeoAyah { get; set; }
        public string GeoIbu { get; set; }
        public string GeoWali { get; set; }
        public string LatitudeAyah { get; set; }
        public string LatitudeIbu { get; set; }
        public string LatitudeWali { get; set; }
        public string LongitudeAyah { get; set; }
        public string LongitudeIbu { get; set; }
        public string LongitudeWali { get; set; }
        public string KecamatanAyah { get; set; }
        public string KecamatanIbu { get; set; }
        public string KecamatanWali { get; set; }
        public string Nik { get; set; }
        public string NoregAktaLahir { get; set; }
        public string NamaLengkapGantiNama { get; set; }
        public string NamaPenyingkatan { get; set; }
        public string Umur { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Line { get; set; }
        public string Whatsapp { get; set; }
        public string WaktuTempuhTk { get; set; }
        public string AgamaKepercayaanLain { get; set; }
        public string TempatIbadah { get; set; }
        public string Negara { get; set; }
        public string StatusAnak { get; set; }
        public string TinggalBersama { get; set; }
        public string StatusTempatTinggal { get; set; }
        public string Provinsi { get; set; }
        public string TransportasiPulang { get; set; }
        public string JarakRumahSmp { get; set; }
        public string JarakRumahSd { get; set; }
        public string JarakRumahTk { get; set; }
        public string TransportasiTk { get; set; }
        public string TransportasiSd { get; set; }
        public string TransportasiSmp { get; set; }
        public string TransportasiPulangTk { get; set; }
        public string TransportasiPulangSd { get; set; }
        public string TransportasiPulangSmp { get; set; }
        public string WaktuTempuhSd { get; set; }
        public string WaktuTempuhSmp { get; set; }
        public string WaktuTempuhSlta { get; set; }
        public string AktaGantiNama { get; set; }
        public string StatusWali { get; set; }
        public string KondisiAyah { get; set; }
        public string KondisiIbu { get; set; }
        public string TanggalMeninggalAyah { get; set; }
        public string StatusPernikahanAyah { get; set; }
        public string StatusPernikahanIbu { get; set; }
        public string TanggalMeninggalIbu { get; set; }
        public string StatusPenaburAyah { get; set; }
        public string StatusPenaburIbu { get; set; }
        public string NikAyah { get; set; }
        public string NikIbu { get; set; }
        public string PenyebabMeninggalAyah { get; set; }
        public string PenyebabMeninggalIbu { get; set; }
        public string NoKtpKitasAyah { get; set; }
        public string NoKtpKitasIbu { get; set; }
        public string NoKkPasporAyah { get; set; }
        public string NoKkPasporIbu { get; set; }
        public string JurusanFakultasAyah { get; set; }
        public string JurusanFakultasIbu { get; set; }
        public string SubagamaAyah { get; set; }
        public string SubagamaIbu { get; set; }
        public string AgamaKepercayaanLainAyah { get; set; }
        public string AgamaKepercayaanLainIbu { get; set; }
        public int? IdgkiAyah { get; set; }
        public int? IdgkiIbu { get; set; }
        public int? IdgkiWali { get; set; }
        public string TempatIbadahAyah { get; set; }
        public string TempatIbadahIbu { get; set; }
        public string PeriodeAyah { get; set; }
        public string PeriodeIbu { get; set; }
        public string NegaraAyah { get; set; }
        public string NegaraIbu { get; set; }
        public string PekerjaanLainAyah { get; set; }
        public string PekerjaanLainIbu { get; set; }
        public string PenghasilanWali { get; set; }
        public string PenghasilanAyah { get; set; }
        public string PenghasilanIbu { get; set; }
        public string ProvinsiAyah { get; set; }
        public string ProvinsiIbu { get; set; }
        public string WhatsappAyah { get; set; }
        public string WhatsappIbu { get; set; }
        public string FacebookAyah { get; set; }
        public string FacebookIbu { get; set; }
        public string InstagramAyah { get; set; }
        public string InstagramIbu { get; set; }
        public string LineAyah { get; set; }
        public string LineIbu { get; set; }
        public string StatusPenaburWali { get; set; }
        public string NikWali { get; set; }
        public string PeriodeWali { get; set; }
        public string NegaraWali { get; set; }
        public string NoKtpKitasWali { get; set; }
        public string NoKkPasporWali { get; set; }
        public string SubagamaWali { get; set; }
        public string AgamaKepercayaanLainWali { get; set; }
        public string TempatIbadahWali { get; set; }
        public string ProvinsiWali { get; set; }
        public string JurusanFakultasWali { get; set; }
        public string PekerjaanLainWali { get; set; }
        public string WhatsappWali { get; set; }
        public string FacebookWali { get; set; }
        public string InstagramWali { get; set; }
        public string LineWali { get; set; }
        public string EmailPenaburFlag { get; set; }
    }
}
